### ISSUE TITLE
[NOTICE] Readme 관련 사항

### ISSUE THREAD

**Issue by wyuinche** [19-2-SKKU-OSS/2019-2-OSS-L8#20]
Readme의 분량이 다른 실제 프로젝트들과 비교했을때 적은 것 같습니다.
프로젝트 설명에 저희가 직접 수정한 내용과 관련해서 원 프로젝트의 사항을 좀 더 보충할 수 있지 않을까요?

**Comment by sunwoong00** [comment]
free python game 부분 내용을 더 추가하면 좋을 것 같습니다.
